// Automatic FlutterFlow imports
import '/backend/backend.dart';
import '/flutter_flow/flutter_flow_theme.dart';
import '/flutter_flow/flutter_flow_util.dart';
import 'index.dart'; // Imports other custom widgets
import '/flutter_flow/custom_functions.dart'; // Imports custom functions
import 'package:flutter/material.dart';
// Begin custom widget code
// DO NOT REMOVE OR MODIFY THE CODE ABOVE!

// ResponsiveShell — caps page content to a phone-sized column and centers it
// on tablet / desktop, painting a neutral surface in the side gutters.
//
// On a phone (window width <= maxWidth) it returns `child` untouched, so the
// mobile layout is 100% unchanged. Above that width it centers the child in a
// ConstrainedBox(maxWidth) on a surface background, so your existing full-bleed
// pages stop stretching edge-to-edge and read as an intentional app column.
//
// USAGE — wrap the widget your page's build() returns:
//
//   @override
//   Widget build(BuildContext context) {
//     return ResponsiveShell(
//       child: Container(          // <- your existing root Container, unchanged
//         width: widget.width ?? double.infinity,
//         height: widget.height ?? double.infinity,
//         ...
//       ),
//     );
//   }
//
// Wrap MainBottomNav the same way so the nav stays aligned with the column.
// Because it collapses to a no-op on phones, it is safe to wrap every page.

class ResponsiveShell extends StatelessWidget {
  const ResponsiveShell({
    super.key,
    required this.child,
    this.maxWidth = 560,
    this.surface = const Color(0xFFECF0F2), // matches Subby _surface
    this.framed = true, // hairline side borders + soft shadow on wide screens
  });

  /// Your existing page content (typically the root Container).
  final Widget child;

  /// The width the content column is capped to on tablet / desktop.
  final double maxWidth;

  /// Colour painted in the side gutters behind the centered column.
  final Color surface;

  /// When true, draws thin side borders and a soft shadow so the column reads
  /// as an app frame on desktop. Set false for a flat, borderless column.
  final bool framed;

  /// App-wide builder helper for `MaterialApp.router(builder: ...)`.
  ///
  /// Wraps the whole navigator so EVERY route is capped + centered on
  /// tablet / desktop and untouched on phones — the entire app, one call.
  /// The logic lives here (custom_code, never regenerated by FlutterFlow),
  /// so main.dart only needs a single line:
  ///
  ///   builder: (context, child) => ResponsiveShell.app(context, child),
  ///
  /// A GitHub Action re-applies that line after each FlutterFlow export.
  static Widget app(
    BuildContext context,
    Widget? child, {
    double maxWidth = 560,
    Color surface = const Color(0xFFECF0F2),
  }) {
    if (child == null) return const SizedBox.shrink();
    final width = MediaQuery.sizeOf(context).width;
    if (width <= maxWidth) return child; // phones: untouched
    return ColoredBox(
      color: surface,
      child: Align(
        alignment: Alignment.topCenter,
        child: ConstrainedBox(
          constraints: BoxConstraints(maxWidth: maxWidth),
          child: DecoratedBox(
            decoration: const BoxDecoration(
              color: Color(0xFFFFFFFF),
              boxShadow: [BoxShadow(color: Color(0x14000000), blurRadius: 24)],
            ),
            child: child,
          ),
        ),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    final width = MediaQuery.sizeOf(context).width;

    // Phone: leave the mobile layout exactly as it is.
    if (width <= maxWidth) return child;

    // Tablet / desktop: center a capped column on the surface.
    return Container(
      color: surface,
      alignment: Alignment.topCenter,
      child: ConstrainedBox(
        constraints: BoxConstraints(maxWidth: maxWidth),
        child: framed
            ? DecoratedBox(
                decoration: const BoxDecoration(
                  color: Color(0xFFFFFFFF),
                  border: Border(
                    left: BorderSide(color: Color(0xFFEAEEF0), width: 1),
                    right: BorderSide(color: Color(0xFFEAEEF0), width: 1),
                  ),
                  boxShadow: [
                    BoxShadow(
                      color: Color(0x14000000),
                      blurRadius: 24,
                      offset: Offset(0, 4),
                    ),
                  ],
                ),
                child: child,
              )
            : child,
      ),
    );
  }
}
